version: '3'

services:
  app:
    build:
      context: .
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=app:*
    tty: true
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - ./src:/app
    networks:
      - backend

networks:
  backend:
